server:
  port: 8004

spring:
  application:
    name: shortlink-stats-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/link?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: xhy_redis
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: stats-producer-group
    send-message-timeout: 2000

short-link:
  stats:
    locale:
      amap-key: 23ea4562d80a83d1dd47922b4913d5e0
