server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
#    active: aggregation
     active: dev
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: xhy_redis
  cloud:
    nacos:
      discovery:
        server-addr: 122.51.107.126:8848
        username: nacos
        password: dA8UJZMYb.KI3szlG4nz3KJKAD4uwK2

sa-token:
  token-style: simple-uuid
  token-name: short-link
  timeout: 1800
  is-concurrent: true
  is-share: true
  is-read-header: true
  is-read-cookie: false
  is-print: false