# 1. 必填：逻辑库名
databaseName: link_db

# 2. 必填：运行模式
mode:
  type: Standalone
  repository:
    type: JDBC

# 3. 数据源配置
dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://$${SHORTLINK_MYSQL_HOST::mysql}:$${SHORTLINK_MYSQL_PORT::3306}/$${SHORTLINK_MYSQL_DATABASE::link}?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: $${SHORTLINK_MYSQL_USERNAME::root}
    password: $${SHORTLINK_MYSQL_PASSWORD::root}
    maximumPoolSize: 50
    minimumIdle: 10
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000
    connectionTestQuery: SELECT 1

  ds_cold:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://$${SHORTLINK_MYSQL_HOST::mysql}:$${SHORTLINK_MYSQL_PORT::3306}/$${SHORTLINK_MYSQL_COLD_DATABASE::link_cold}?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: $${SHORTLINK_MYSQL_USERNAME::root}
    password: $${SHORTLINK_MYSQL_PASSWORD::root}
    maximumPoolSize: 20
    minimumIdle: 5
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000
    connectionTestQuery: SELECT 1

rules:
  - !SHARDING
    autoTables:
      t_link:
        actualDataSources: ds_0
        shardingStrategy:
          standard:
            shardingColumn: gid
            shardingAlgorithmName: t_link_hash_mod
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake

      t_link_goto:
        actualDataSources: ds_0
        shardingStrategy:
          standard:
            shardingColumn: full_short_url
            shardingAlgorithmName: t_link_goto_hash_mod
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake

      t_group:
        actualDataSources: ds_0
        shardingStrategy:
          standard:
            shardingColumn: username
            shardingAlgorithmName: t_group_hash_mod
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake

    shardingAlgorithms:
      t_link_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16

      t_link_goto_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16

      t_group_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16

    keyGenerators:
      snowflake:
        type: SNOWFLAKE
        props:
          worker-id: 1

  - !SINGLE
    tables:
      - "ds_0.*"
      - "ds_cold.t_link_cold"
      - "ds_cold.t_link_goto_cold"
      - "ds_cold.t_link_history"
      - "ds_cold.t_link_goto_history"
    defaultDataSource: ds_0

props:
  sql-show: true
