global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: shortlink-host-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8000
          - host.docker.internal:8001
          - host.docker.internal:8002
          - host.docker.internal:8003
          - host.docker.internal:8004
          - host.docker.internal:8005

  - job_name: shortlink-compose-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - gateway:8000
          - aggregation:8003
          - stats:8004
          - risk:8005
