server:
  port: 8002

spring:
  application:
    name: short-link-admin
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml

  data:
    redis:
      host: 172.28.64.14
      port: 6379
      password: xhy_redis
  cloud:
    nacos:
      discovery:
        server-addr: 122.51.107.126:8848
        username: nacos
        password: dA8UJZMYb.KI3szlG4nz3KJKAD4uwK2

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler # 分页插件
    map-underscore-to-camel-case: true # 驼峰映射 默认自动开启
  global-config:
    db-config:
      logic-delete-field: delFlag # 逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值 默认为0

short-link:
  group:
    max-num: 20
  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 20


