spring:
  cloud:
    gateway:
      routes:
        - id: shortlink-user-service
          uri: lb://shortlink-user-service
          predicates:
            - Path=/api/short-link/admin/**
          filters:
            - name: TokenValidate
              args:
                whitePathList:
                  - /api/short-link/admin/v1/user/login
                  - /api/short-link/admin/v1/user/has-username

        - id: shortlink-stats-service
          uri: lb://shortlink-stats-service
          predicates:
            - Path=/api/short-link/v1/stats/**
          filters:
            - name: TokenValidate
              args:
                whitePathList: []

        - id: shortlink-project-service
          uri: lb://shortlink-project-service
          predicates:
            - Path=/api/short-link/**
          filters:
            - name: TokenValidate
              args:
                whitePathList: []
