server:
  port: 8000
spring:
  application:
    name: shortlink-gateway-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import:
      - optional:nacos:shortlink-common.yaml
      - optional:nacos:${spring.application.name}.yaml
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:127.0.0.1}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:xhy_redis}
  cloud:
    nacos:
      username: ${SPRING_CLOUD_NACOS_USERNAME:${SPRING_CLOUD_NACOS_DISCOVERY_USERNAME:nacos}}
      password: ${SPRING_CLOUD_NACOS_PASSWORD:${SPRING_CLOUD_NACOS_DISCOVERY_PASSWORD:nacos}}
      discovery:
        server-addr: ${SPRING_CLOUD_NACOS_SERVER_ADDR:${SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR:127.0.0.1:8848}}
        username: ${spring.cloud.nacos.username}
        password: ${spring.cloud.nacos.password}
        namespace: ${NACOS_NAMESPACE:}
      config:
        server-addr: ${SPRING_CLOUD_NACOS_SERVER_ADDR:${SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR:127.0.0.1:8848}}
        username: ${spring.cloud.nacos.username}
        password: ${spring.cloud.nacos.password}
        file-extension: yaml
        group: DEFAULT_GROUP
        namespace: ${NACOS_NAMESPACE:}
        refresh-enabled: true

short-link:
  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 20

sa-token:
  token-style: simple-uuid
  token-name: short-link
  timeout: 1800
  is-concurrent: true
  is-share: true
  is-read-header: true
  is-read-cookie: false
  is-print: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.9,0.95,0.99
