server:
  port: 8003
  tomcat:
    threads:
      max: 500
      min-spare: 50
    connection-timeout: 20000

spring:
  application:
    name: shortlink-aggregation-service
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${DATABASE_ENV:${database.env:dev}}.yaml
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:127.0.0.1}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:xhy_redis}
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: ${SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR:127.0.0.1:8848}
        username: ${SPRING_CLOUD_NACOS_DISCOVERY_USERNAME:nacos}
        password: ${SPRING_CLOUD_NACOS_DISCOVERY_PASSWORD:nacos}

# user-service 业务配置
short-link:
  group:
    max-num: 20
  # project-service 业务配置
  cache:
    local:
      initial-capacity: 100
      maximum-size: 10000
      expire-after-write: 30
  create:
    strategy: bloom-filter
  domain:
    default: "${SHORT_LINK_DOMAIN_DEFAULT:nurl.ink:8003}"
  cold-data:
    enabled: true
    days: 90
    batch-size: 200
    cron: "0 30 2 * * ?"
    rehot:
      threshold: 1000
    grace-days: 30
  goto-domain:
    white-list:
      enable: false
      names: '拿个offer,知乎,掘金,博客园,github'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com
        - github.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:127.0.0.1:9876}
  producer:
    group: short-link_project-service_stats-save_pg
    topic: short-link_project-service_topic
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
  consumer:
    group: short-link_project-service_stats-save_cg

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.9,0.95,0.99
